[build]
  command = "npm run build"
  publish = "src/static"
  functions = "build/functions"

[[redirects]]
  from = "src/static/*"
  to = "/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/render-page"
  status = 200
